version: '3.0'

services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    volumes:
      - ~/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200